name: PLStats.com
description: Trying another approach on football data
meta_description: "PLStats.com blog page."

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
excerpt_separator: ""

# Details for the RSS feed generator
url:            'blog.plstats.com'
author:         'Friðrik'
