name: Plstats.com blog
description: Blog about how we are trying another approach on football data.
meta_description: "Plstats.com blog page. "

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog.plstats.com'
author:         'Friðrik'
